# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Localsubs < Formula
  desc "Local AI subtitle translation helper for streaming video"
  homepage "https://github.com/aiden1020/localsubs"
  version "0.2.0"

  depends_on "llama.cpp"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/aiden1020/localsubs/releases/download/v0.2.0/localsubs_darwin_amd64.tar.gz"
    sha256 "44830daaeac38b8a16d11c5fb7bae4b2d4be22961466cf61220fcf7d8621520b"

    define_method(:install) do
      bin.install "localsubs"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/aiden1020/localsubs/releases/download/v0.2.0/localsubs_darwin_arm64.tar.gz"
    sha256 "509b70fe9197db20464f00c203fa8c040110405e64de09316de458ef6e077c80"

    define_method(:install) do
      bin.install "localsubs"
    end
  end

  def caveats
    <<~EOS
      Get started:
        localsubs model download   # download translation model (~424 MB)
        localsubs install           # connect to Chrome
    EOS
  end

  test do
    assert_match "localsubs", shell_output("#{bin}/localsubs version")
  end
end
