# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Localsubs < Formula
  desc "Local AI subtitle translation helper for streaming video"
  homepage "https://github.com/aiden1020/localsubs"
  version "0.3.0"

  depends_on "llama.cpp"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/aiden1020/localsubs/releases/download/v0.3.0/localsubs_darwin_amd64.tar.gz"
    sha256 "7512ebc75ed9cdd20476889f29569013dbfe4058340225bc26889c85b18663d1"

    define_method(:install) do
      bin.install "localsubs"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/aiden1020/localsubs/releases/download/v0.3.0/localsubs_darwin_arm64.tar.gz"
    sha256 "f2ceb36614136b341788f7d0db5f10cf2d354e8d4124b4c47e27c25ab03d3f19"

    define_method(:install) do
      bin.install "localsubs"
    end
  end

  def caveats
    <<~EOS
      Get started:
        localsubs model download   # download translation model (~350 MB)
        localsubs install           # connect to Chrome
    EOS
  end

  test do
    assert_match "localsubs", shell_output("#{bin}/localsubs version")
  end
end
