# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Localsubs < Formula
  desc "Local AI subtitle translation helper for streaming video"
  homepage "https://github.com/aiden1020/localsubs"
  version "0.3.4"

  depends_on "llama.cpp"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/aiden1020/localsubs/releases/download/v0.3.4/localsubs_darwin_amd64.tar.gz"
    sha256 "4f9853b50f92100ff76955c14e95154e645fb1ab843aa3cdb346b748a6ecc5f5"

    define_method(:install) do
      bin.install "localsubs"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/aiden1020/localsubs/releases/download/v0.3.4/localsubs_darwin_arm64.tar.gz"
    sha256 "34a6838f07af984a3f62eb86b18d9d17043c02f8e7bd2b5c5e5ff5d01cf54394"

    define_method(:install) do
      bin.install "localsubs"
    end
  end

  def caveats
    <<~EOS
      Get started:
        localsubs setup   # download the model and install Chrome integration
    EOS
  end

  test do
    assert_match "localsubs", shell_output("#{bin}/localsubs version")
  end
end
