# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Localsubs < Formula
  desc "Local AI subtitle translation helper for streaming video"
  homepage "https://github.com/aiden1020/localsubs"
  version "0.3.2"

  depends_on "llama.cpp"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/aiden1020/localsubs/releases/download/v0.3.2/localsubs_darwin_amd64.tar.gz"
    sha256 "c7d74d118103630e892f627592d387db30f187bb48a469848dcdbe5bcd7d6e95"

    define_method(:install) do
      bin.install "localsubs"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/aiden1020/localsubs/releases/download/v0.3.2/localsubs_darwin_arm64.tar.gz"
    sha256 "e4ba0e8bc88ce03e9a3833c363263060bd28ac4eb3364bc62a1c2bd845458a2a"

    define_method(:install) do
      bin.install "localsubs"
    end
  end

  def caveats
    <<~EOS
      Get started:
        localsubs model download   # download translation model (~350 MB)
        localsubs install           # connect to Chrome
    EOS
  end

  test do
    assert_match "localsubs", shell_output("#{bin}/localsubs version")
  end
end
