# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Localsubs < Formula
  desc "Local AI subtitle translation helper for streaming video"
  homepage "https://github.com/aiden1020/localsubs"
  version "0.3.3"

  depends_on "llama.cpp"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/aiden1020/localsubs/releases/download/v0.3.3/localsubs_darwin_amd64.tar.gz"
    sha256 "047a0d030c10342a38da4fd5c03d43555a8781de048dceb6b926f13336233dcd"

    define_method(:install) do
      bin.install "localsubs"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/aiden1020/localsubs/releases/download/v0.3.3/localsubs_darwin_arm64.tar.gz"
    sha256 "848535762177c58d4a960260e097dcb7339ec64bca3db4f41ec0c88059152de5"

    define_method(:install) do
      bin.install "localsubs"
    end
  end

  def caveats
    <<~EOS
      Get started:
        localsubs setup   # download the model and install Chrome integration
    EOS
  end

  test do
    assert_match "localsubs", shell_output("#{bin}/localsubs version")
  end
end
